# Generated by Django 4.2.5 on 2024-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('propic', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
