# Generated by Django 4.2.5 on 2024-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=100)),
                ('prodprice', models.IntegerField()),
                ('proimg', models.ImageField(upload_to='', verbose_name='images/')),
                ('prosize', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
