# Generated by Django 4.2.5 on 2024-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sellproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='category',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
