# Generated by Django 4.2.5 on 2024-04-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
