# Generated by Django 4.2.4 on 2024-05-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_selected_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sellproduct')),
            ],
        ),
    ]
