# Generated by Django 4.2.4 on 2024-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wishpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishpage',
            name='selectedsize',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
