# Generated by Django 4.2.4 on 2024-05-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wishpage_selectedsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishpage',
            old_name='selectedsize',
            new_name='selected_size',
        ),
    ]
