# Generated by Django 4.2.4 on 2024-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_selectedsize_wishpage_selected_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adressdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress1', models.CharField(max_length=200)),
                ('adress2', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
