# Generated by Django 4.2.4 on 2024-05-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_adressdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressdet',
            name='userdetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.userregister'),
            preserve_default=False,
        ),
    ]
