# Generated by Django 4.2.4 on 2024-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_adressdet_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressdet',
            name='contact_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
