# Generated by Django 4.2.4 on 2024-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_pic',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
